name: release
"on":
  push:
    branches:
      - master
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3
        with:
          cache: npm
          node-version: 16
      - run: npm ci
      - run: npm run build
      - run: rm .gitignore
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GR2M_PAT_FOR_SEMANTIC_RELEASE }}
      - run: >-
          git push
          https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          HEAD:refs/heads/v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
