on: [push]
name: Test
jobs:
  readmeExample:
    name: "[TEST] README example"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          cache: npm
      - run: "npm ci"
      - run: "npm run build"
      - name: "Get latest release of ${{ github.repository }}"
        uses: ./
        id: get_latest_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: octokit
          repo: request-action
      - run: "echo latest release: '${{ fromJson(steps.get_latest_release.outputs.data).tag_name }}'"

      # Create check run
      - name: "Create check run for ${{ github.sha }}"
        uses: ./
        id: create_check_run
        with:
          route: POST /repos/{owner}/{repo}/check-runs
          owner: octokit
          repo: request-action
          name: "Test check run"
          head_sha: ${{ github.sha }}
          output: | # The | is significant!
            title: Test check run title
            summary: A summary of the test check run
            images:
              - alt: Test image
                image_url: https://octodex.github.com/images/jetpacktocat.png
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Update check run to completed, succesful status
      - name: "Update check run ${{ fromJson(steps.create_check_run.outputs.data).id }} "
        uses: ./
        id: update_check_run
        with:
          route: PATCH /repos/{owner}/{repo}/check-runs/{check_run_id}
          owner: octokit
          repo: request-action
          check_run_id: ${{ fromJson(steps.create_check_run.outputs.data).id }}
          conclusion: "success"
          status: "completed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # handle error
      - name: "Handle error"
        continue-on-error: true
        uses: ./
        id: get_release
        with:
          route: GET /repos/{owner}/{repo}/releases/v0.9.9
          owner: octokit
          repo: request-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo Release cound not be found. Request failed with status ${{ steps.get_release.outputs.status }}"
        if: ${{ failure() }}

  issues:
    name: "[TEST] Issues"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          cache: npm
      - run: "npm ci"
      - run: "npm run build"

      # See https://github.com/octokit/request-action/issues/71
      - name: "Un-encode {repo} URL parameter when it's set to github.repository (#71)"
        uses: ./
        with:
          route: GET /repos/{repository}
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
